Hooks:PostHook( NetworkAccountSTEAM, "_set_presences", "nepmenu_setup_new_presences", function(self)
	Steam:set_rich_presence("infamy", managers.experience:current_rank())
	Steam:set_rich_presence("amount_skillpoints_mastermind", managers.skilltree:get_tree_progress_2("mastermind"))
	Steam:set_rich_presence("amount_skillpoints_enforcer", managers.skilltree:get_tree_progress_2("enforcer"))
	Steam:set_rich_presence("amount_skillpoints_technician", managers.skilltree:get_tree_progress_2("technician"))
	Steam:set_rich_presence("amount_skillpoints_ghost", managers.skilltree:get_tree_progress_2("ghost"))
	Steam:set_rich_presence("amount_skillpoints_fugitive", managers.skilltree:get_tree_progress_2("hoxton"))
	Steam:set_rich_presence("loadout_data", managers.blackmarket:player_loadout_data())
end)
